version: "3"

services:
    client:
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./certs:/etc/nginx/certs:ro
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - ../build:/usr/share/nginx/html